website:
  title: "Sam Mooney"
  favicon: images/favicon/favicon.ico
  page-navigation: false
  reader-mode: false
  page-footer:
    #background: "#b6babe"
    background: "#6f6f6f"
    right: "Inspired by brunbattery.github.io/NetworkNotes/"
    left: ""

  sidebar:
    #background: dark
    logo: ""
    pinned: true
    align: center
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/sam-d-mooney/
        text: "LinkedIn"
      - icon: github
        href: https://www.github.com/samireland/
        text: "GitHub"
      - icon: youtube
        href: https://www.youtube.com/@SamMooneyTech
        text: "Tech YouTube"
        

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Hello
        

      - section: Cisco Modeling Labs
        contents: 
          - What_is_CML?.md
          - Provision_Templates.md
          - content/Labs.md  




      - section: CCNP ENCOR
        contents:

          - section: Study Material
            contents: 
              - Study Material.md
              - Podcasts.md

          - section: Network Switching
            contents: 
              - SpanningTree.md
              - Layer2PortAggregation.md
              - QOS.md

          - section: Network Routing
            contents:
              - BGP.md
              - OSPF.md
              - EIGRP.md
              - NAT.md
              - content/Multicast.md
              - content/Multicast-Twitch-TV.md
              - content/Multicast-Youtube-Live.md

          - section: Virtualization
            contents: 
              - Virtualizations.md
              - content/VTI_with_IPSEC.md

          - section: Wireless
            contents: 
              - Wireless.md

          - section: Network Assurance
            contents: 
              - Network Assurance.md

          - section: Security
            contents: 
              - content/AccessLists.md
              - content/COPP.md
              - AAA.md

          - section: Automation
            contents: 
              - Automation.md
              - Python.md

          - section: Software Defined Networking
            contents:
              - Cisco_DNA-Center.md
              - Cisco_SD-Access.md
              - Cisco_SD-WAN.md
              - APIs_DNA-Center_vManage.md

      - section: Fortinet
        contents:

          - section: Fortimanager Automation
            contents: 
              - Study Material.md
              - Podcasts.md

          - section: AWS Direct Connect
            contents: 
              - DXCON.md


      - section: AWS Advanced Network Specialty
        contents:

          - section: Study Material
            contents: 
              - Study Material.md
              - Podcasts.md

          - section: AWS Direct Connect
            contents: 
              - DXCON.md



      - section: Music
        contents: 
          - Videos.md



format:
  html:
    theme:
      - darkly
      - custom.scss
    toc: true

project:
  type: website

execute:
  freeze: auto
